name = "TryFit"
client_id = "801b072184a9733e9c66dc11391a28a5"
application_url = "https://tryfit-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "testing-ashif.myshopify.com"

[access_scopes]
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://tryfit-production.up.railway.app/auth/callback",
  "https://tryfit-production.up.railway.app/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[webhooks.privacy_compliance]
customer_data_request_url = "/webhooks"
customer_deletion_url = "/webhooks"
shop_deletion_url = "/webhooks"

[app_proxy]
url = "https://tryfit-production.up.railway.app/app/proxy/tryon"
subpath = "tryon"
prefix = "apps"
